### ISSUE TITLE
Custom Pageformat 24 labels per A4 Page generation

### ISSUE THREAD

**Issue by 123bistami** [baltpeter/internetmarke-php#1]
Hello,

I would like 24 labels with sender and receiver adress included on the label per page, but i not found pre defined label format that i get with retrievePageformats method where this is possible with adress, the documentation of the Internetmarke api says that custom pageformats mot possible, so i think i have to produce 24 labels for e.g. Brother defined label and merge it by me to a A4 Pdf Page, knows somebody a better smarter solution, pls help.

**Comment by baltpeter** [comment]
Hi,

to be honest, I am not quite sure how you would want to achieve that.
Labels with addresses look like this (see the "Examples" wiki page): 

![Stamp](https://camo.githubusercontent.com/8ae157aa90b83b0681611c07e6c76fe43b8c8a7f/68747470733a2f2f692e696d6775722e636f6d2f624637646c34592e706e67)

There is simply not enough space for 24 of them on an A4 paper.

Regardless, I am not aware of any other way to achieve what you are trying to do. As you said, the Internetmarke API only supports the pre-defined formats and there is no way to specify your own ones, so you would have to modify the PNGs or PDFs directly yourself.

**Comment by 123bistami** [comment]
i know the smallest label with address is ~ 88 x 60 i think, i need 76 x 36 i think, i will first produce 24 label in the size 88 x 60 and than merge it to one a4 paper with a library like FPDF, i see a company that provide 24 labels with address per page, what do you think...

**Comment by baltpeter** [comment]
It is certainly technically possible to do that, yes.

Some things that I would keep in mind, though:

* It will probably be quite annoying to implement that. I don't have experience with FPDF, so I can't exactly estimate the amount of work but I know that there are some quirks to the PDFs from the Internetmarke.
* You will have to make sure that your labels still comply with the requirements set by Deutsche Post. As far as I know, there is no (public) documentation for these standards for the Internetmarke, so you will probably contact DP and ask them if the labels are still valid, otherwise your letters might not get delivered.

In the end, if you are manipulating the PDF anyway, it might be easier to just order stamps without addresses from the API and then add the addresses yourself. You would still have to make sure the labels are valid though…

**Comment by 123bistami** [comment]
i dont know why DP not use this size with address if its possible by labels like for brother why its not possible for 76 x 36 defined labels, just a little bit smaller than brothers label?

**Comment by baltpeter** [comment]
I am sorry but that is not something that I can answer, you will have to contact Deutsche Post for that.
