### ISSUE TITLE
Error 503 if portokasse-mode not prepaid

### ISSUE THREAD

**Issue by jav666** [baltpeter/internetmarke-php#14]
hiho, we got a 503 error, after our portokasse was switchet to "Postpaid" (from '"prepaid" i think). with prepaid your class worked well. is there a context?

regards and many thanks
joey

**Comment by niels-numbers** [comment]
I just tried out my own portokasse url and it does not work at the moment.

I looked up at 1C4A-P-Set, there was no change in the docs since 2016. 

I don't know what you mean with "postpaid", but 503 error means usually server overload or so.

Looks to me like its an issue with Deutsche Post, they also changed the portokasse url to https://portokasse.deutschepost.de/portokasse/#!/marketplace/payment/:status

I have send them a mail through contact form, but in my experience it may take up to two weeks till you get a respond

**Comment by jav666** [comment]
update: we got the 503 error only on a specific product-ID. the other IDs worked well. we stay in contact with the support from ProdWS (portokasse) in this case. so i think its not an "internetmarke-php" issue. thanks for response!

**Comment by niels-numbers** [comment]
Deutsche Post responded to me that they had an issue with port 8443. Now its fixed and I can also normally access the porto kasse.

So anyway, I think this issue can be closed right?

**Comment by baltpeter** [comment]
Sounds good, thanks for the update!
