### ISSUE TITLE
Zusatzleistungen / Trackingcode

### ISSUE THREAD

**Issue by pneun** [baltpeter/internetmarke-php#4]
Hallo,

ist es möglich auch Zusatzleistungen wie Einschreiben zu buchen?
Ich denke man müsste dann eine andere ProductId übergeben.
Gibt es einen Weg die Ids auszulesen?

**Comment by baltpeter** [comment]
Hi,

you can absolutely buy additional services like Einschreiben. As you say, every possible combination of products with additional services is assigned a separate product ID by Deutsche Post. You can get these IDs either by using their separate ProdWS service or an Excel spreadsheet which you can request from your contact at Deutsche Post.

The tracking code for Einschreiben and similar services is returned in the response to checkoutShoppingCartP(df|ng)(). I don't remember the exact name since I don't use that feature myself but you can either try it yourself or have a look at the official API documentation.

Cheers,
Benjamin

**Comment by pneun** [comment]
Thank you.
Found the Ids here:
https://www.deutschepost.de/content/dam/mlm.nf/dpag/technische_downloads/update_internetmarke/ppl_v390.csv
